"""Generate the bundle's pyproject.toml and manifest.json from the repo's own metadata.

Anything that must agree with the published package — name, version, licence, URLs, the
Python floor, the dependency ceilings — is read from the repo's `pyproject.toml`, so the
bundle cannot drift from what it packages. Only the copy aimed at the person installing
the bundle is literal here; that is deliberately different text from the PyPI summary,
which is written for developers.
"""

import asyncio
import json
import os
import pathlib
import sys
import tempfile
import tomllib

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]

PUBLISHER = "Delta Exchange"
KEYWORDS = ["trading", "crypto", "options", "futures", "market-data"]

# The display name and the short description are not here: the server declares both in its
# own handshake, so they live in `delta_exchange_mcp.identity` and this reads them from
# there. Importing that is deferred to where it is used, for the reason `tool_entries`
# gives — importing the package runs `__init__`, and that must not happen before the
# DELTA_ environment is scrubbed.

LONG_DESCRIPTION = (
    "Ask about Delta Exchange India in plain English: live prices, option chains, "
    "order books, funding and open-interest history, plus your own positions, orders, "
    "fills and balances.\n\n"
    "**Market data needs no setup.** Account and trading tools remain visible, but each "
    "call checks its authorization before it reaches Delta.\n\n"
    "**Connect outside the conversation.** An account call returns a Manage Connection "
    "link to a short-lived page on your machine. Enter the API key and secret there. The "
    "page sends them directly to the local MCP service and stores them in the operating-"
    "system credential service when available. The assistant does not receive them.\n\n"
    "**Trading requires browser consent.** Manage Connection binds approval to the exact "
    "MCP client, environment, and credential identity. Changing any of them turns trading "
    "off. Production approval requires a warning acknowledgement. There is no order-size "
    "cap, and orders use contracts rather than coins. Every mutation is audit-logged by "
    "default."
)


def project() -> dict:
    """The repo's own [project] table — the single source of truth for shared metadata."""
    with (REPO / "pyproject.toml").open("rb") as f:
        proj = tomllib.load(f)["project"]
    # render_manifest copies this straight through, and the manifest schema wants an SPDX
    # string. PEP 639 spells it that way; the older `{ text = "MIT" }` table would land in
    # the JSON as a nested object and fail validation with a message that names the field
    # and not the cause. Checked here because this is the one place the file is read.
    if not isinstance(proj.get("license"), str):
        raise SystemExit(
            f"[project].license must be an SPDX string, got {proj.get('license')!r} — "
            "the manifest schema has no place for the table form"
        )
    return proj


def wheel_name(proj: dict) -> str:
    return f"{proj['name'].replace('-', '_')}-{proj['version']}-py3-none-any.whl"


def render_pyproject(proj: dict) -> str:
    """The bundle's own project file, pinned to the vendored wheel.

    The dependency ranges are copied from the repo rather than restated. The SDK moved its
    server class across a major, so a bundle that resolved outside the repo's range would
    die at import, in either direction.
    """
    deps = [f"{proj['name']}=={proj['version']}", *proj["dependencies"]]
    rendered = ",\n".join(f'    "{d}"' for d in deps)
    return (
        "# Generated by make_bundle.py — edit that, not this.\n"
        "[project]\n"
        f'name = "{proj["name"]}-bundle"\n'
        f'version = "{proj["version"]}"\n'
        f'requires-python = "{proj["requires-python"]}"\n'
        f"dependencies = [\n{rendered},\n]\n"
        "\n[tool.uv.sources]\n"
        f'{proj["name"]} = {{ path = "wheels/{wheel_name(proj)}" }}\n'
    )


async def tool_entries() -> list[dict[str, str]]:
    """Introspect the server's stable tool list in an isolated environment.

    Every DELTA_ variable is cleared before the ones that matter are set, so the manifest
    depends only on the source being packaged and never on the shell the build ran in.
    Credentials and consent change request-time authorization only; they never change this
    list. `tools_generated` is false, so the generated manifest must match it exactly.
    """
    for name in [name for name in os.environ if name.startswith("DELTA_")]:
        del os.environ[name]

    # One scratch directory for everything the introspection writes, removed on the way out.
    # A bare mkdtemp is removed by nobody, so every build would leave a directory behind for
    # the operating system to reap eventually — trading files left in the home directory for
    # files left in /tmp, which is not the fix it looks like.
    with tempfile.TemporaryDirectory(prefix="mcpb-manifest-") as scratch:
        os.environ.update({
            "DELTA_MCP_CONFIG_FILE": str(pathlib.Path(scratch) / "config.env"),
        })
        from delta_exchange_mcp.server import build_server

        tools = await build_server().list_tools()

    return [
        {
            "name": t.name,
            "description": (t.description or "").strip().splitlines()[0].strip(),
        }
        for t in sorted(tools, key=lambda t: t.name)
    ]


def render_manifest(proj: dict, tools: list[dict[str, str]]) -> dict:
    # Safe here and not at module scope: `main` runs `tool_entries` first, which scrubs the
    # DELTA_ environment before anything imports the package.
    from delta_exchange_mcp.identity import DISPLAY_NAME, SHORT_DESCRIPTION

    urls = proj.get("urls", {})
    return {
        "manifest_version": "0.4",
        "name": proj["name"],
        "display_name": DISPLAY_NAME,
        "version": proj["version"],
        "description": SHORT_DESCRIPTION,
        "long_description": LONG_DESCRIPTION,
        "author": {"name": PUBLISHER, "url": urls["Homepage"]},
        "repository": {"type": "git", "url": urls["Repository"]},
        "homepage": urls["Homepage"],
        "documentation": urls["Documentation"],
        "support": urls["Issues"],
        "icon": "icon.png",
        "license": proj["license"],
        "keywords": KEYWORDS,
        "server": {
            "type": "uv",
            "entry_point": "server/main.py",
            "mcp_config": {
                "command": "uv",
                "args": [
                    "run",
                    "--directory",
                    "${__dirname}",
                    "--frozen",
                    "python",
                    "server/main.py",
                ],
            },
        },
        "tools": tools,
        "tools_generated": False,
        "compatibility": {
            "claude_desktop": ">=0.10.0",
            "platforms": ["darwin", "win32", "linux"],
            "runtimes": {"python": proj["requires-python"]},
        },
    }


def main() -> None:
    what = sys.argv[1]
    proj = project()

    if what == "version":
        print(proj["version"])
    elif what == "wheel-name":
        print(wheel_name(proj))
    elif what == "pyproject":
        (HERE / "pyproject.toml").write_text(render_pyproject(proj))
        print(f"wrote pyproject.toml (deps from {REPO.name}/pyproject.toml)")
    elif what == "manifest":
        tools = asyncio.run(tool_entries())
        out = HERE / "manifest.json"
        out.write_text(json.dumps(render_manifest(proj, tools), indent=2) + "\n")
        print(f"wrote manifest.json ({len(tools)} tools, version {proj['version']})")
    else:
        raise SystemExit(f"unknown target: {what}")


if __name__ == "__main__":
    main()
