"""Generate the bundle's pyproject.toml and manifest.json from the repo's own metadata.

Anything that must agree with the published package — name, version, licence, URLs, the
Python floor, the dependency ceilings — is read from the repo's `pyproject.toml`, so the
bundle cannot drift from what it packages. Only the copy aimed at the person installing
the bundle is literal here; that is deliberately different text from the PyPI summary,
which is written for developers.
"""

import asyncio
import json
import os
import pathlib
import sys
import tempfile
import tomllib

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]

PUBLISHER = "Delta Exchange"
KEYWORDS = ["trading", "crypto", "options", "futures", "market-data"]

# The display name and the short description are not here: the server declares both in its
# own handshake, so they live in `delta_exchange_mcp.identity` and this reads them from
# there. Importing that is deferred to where it is used, for the reason `tool_entries`
# gives — importing the package runs `__init__`, and that must not happen before the
# DELTA_ environment is scrubbed.

LONG_DESCRIPTION = (
    "Ask about Delta Exchange India in plain English: live prices, option chains, "
    "order books, funding and open-interest history, plus your own positions, orders, "
    "fills and balances.\n\n"
    "**Market data needs no account connection.** Account calls open a short-lived browser "
    "page when a connection is missing. Enter the API key and secret there. They do not pass "
    "through the conversation or an MCP tool call. When available, the server stores them "
    "in macOS Keychain, Windows Credential Manager, or Linux Secret Service. Otherwise it "
    "keeps the connection and trading consent in process memory for that process. The server "
    "does not use a plaintext fallback.\n\n"
    "**Trading needs separate browser approval.** Trading tools stay visible so clients keep "
    "one stable tool list. A dry run sends no mutation and needs no trading approval. A real "
    "trading call opens the approval page when approval is missing. Approval does not execute "
    "the pending trade. Submit a new call if the trade is still wanted.\n\n"
    "Production trading can place real orders with no size cap. Orders are sized in contracts, "
    "not coins. The approval page requires a separate production acknowledgement. By default, "
    "every real mutation is written to an owner-only audit log."
)


def project() -> dict:
    """The repo's own [project] table — the single source of truth for shared metadata."""
    with (REPO / "pyproject.toml").open("rb") as f:
        proj = tomllib.load(f)["project"]
    # render_manifest copies this straight through, and the manifest schema wants an SPDX
    # string. PEP 639 spells it that way; the older `{ text = "MIT" }` table would land in
    # the JSON as a nested object and fail validation with a message that names the field
    # and not the cause. Checked here because this is the one place the file is read.
    if not isinstance(proj.get("license"), str):
        raise SystemExit(
            f"[project].license must be an SPDX string, got {proj.get('license')!r} — "
            "the manifest schema has no place for the table form"
        )
    return proj


def wheel_name(proj: dict) -> str:
    return f"{proj['name'].replace('-', '_')}-{proj['version']}-py3-none-any.whl"


def render_pyproject(proj: dict) -> str:
    """The bundle's own project file, pinned to the vendored wheel.

    The dependency ranges are copied from the repo rather than restated. The SDK moved its
    server class across a major, so a bundle that resolved outside the repo's range would
    die at import, in either direction.
    """
    deps = [f"{proj['name']}=={proj['version']}", *proj["dependencies"]]
    rendered = ",\n".join(f'    "{d}"' for d in deps)
    return (
        "# Generated by make_bundle.py — edit that, not this.\n"
        "[project]\n"
        f'name = "{proj["name"]}-bundle"\n'
        f'version = "{proj["version"]}"\n'
        f'requires-python = "{proj["requires-python"]}"\n'
        f"dependencies = [\n{rendered},\n]\n"
        "\n[tool.uv.sources]\n"
        f'{proj["name"]} = {{ path = "wheels/{wheel_name(proj)}" }}\n'
    )


async def tool_entries() -> list[dict[str, str]]:
    """Introspect the server to list its stable tool registry.

    The manifest must not depend on credentials, trading consent, a developer's keyring, or
    DELTA_ values inherited from the build shell. The in-memory stores below make the build
    independent of all four. Runtime authorization happens when a tool is called and never
    changes this list.
    """
    for name in [name for name in os.environ if name.startswith("DELTA_")]:
        del os.environ[name]

    with tempfile.TemporaryDirectory(prefix="mcpb-manifest-") as scratch:
        os.environ.update({
            "DELTA_MCP_AUDIT": "off",
            "DELTA_MCP_CONFIG_FILE": str(pathlib.Path(scratch) / "config.env"),
        })
        from delta_exchange_mcp import debug_log
        from delta_exchange_mcp import store
        from delta_exchange_mcp.auth.connection import ConnectionService
        from delta_exchange_mcp.auth.consent import ConsentStore, MemoryConsentBackend
        from delta_exchange_mcp.auth.store import (
            CredentialSource,
            CredentialStore,
            MemoryMetadata,
            MemorySecretBackend,
        )
        from delta_exchange_mcp.server import build_server

        service = ConnectionService.open(
            credentials=CredentialStore(
                MemorySecretBackend(),
                MemoryMetadata(),
                CredentialSource.MEMORY,
            ),
            consent=ConsentStore(
                store.path().with_name("consent.json"),
                secure_backend_available=False,
                memory_backend=MemoryConsentBackend(),
            ),
        )
        server = build_server(connection_service=service)
        try:
            tools = await server.list_tools()
        finally:
            await server.close_live_client()
            debug_log.shutdown()

    return [
        {
            "name": t.name,
            "description": (t.description or "").strip().splitlines()[0].strip(),
        }
        for t in sorted(tools, key=lambda t: t.name)
    ]


def render_manifest(proj: dict, tools: list[dict[str, str]]) -> dict:
    # Safe here and not at module scope: `main` runs `tool_entries` first, which scrubs the
    # DELTA_ environment before anything imports the package.
    from delta_exchange_mcp.identity import DISPLAY_NAME, SHORT_DESCRIPTION

    urls = proj.get("urls", {})
    return {
        "manifest_version": "0.4",
        "name": proj["name"],
        "display_name": DISPLAY_NAME,
        "version": proj["version"],
        "description": SHORT_DESCRIPTION,
        "long_description": LONG_DESCRIPTION,
        "author": {"name": PUBLISHER, "url": urls["Homepage"]},
        "repository": {"type": "git", "url": urls["Repository"]},
        "homepage": urls["Homepage"],
        "documentation": urls["Documentation"],
        "support": urls["Issues"],
        "icon": "icon.png",
        "license": proj["license"],
        "keywords": KEYWORDS,
        "server": {
            "type": "uv",
            "entry_point": "server/main.py",
            "mcp_config": {
                "command": "uv",
                "args": [
                    "run",
                    "--directory",
                    "${__dirname}",
                    "--frozen",
                    "python",
                    "server/main.py",
                ],
            },
        },
        "tools": tools,
        "tools_generated": False,
        "compatibility": {
            "claude_desktop": ">=0.10.0",
            "platforms": ["darwin", "win32", "linux"],
            "runtimes": {"python": proj["requires-python"]},
        },
    }


def main() -> None:
    what = sys.argv[1]
    proj = project()

    if what == "version":
        print(proj["version"])
    elif what == "wheel-name":
        print(wheel_name(proj))
    elif what == "pyproject":
        (HERE / "pyproject.toml").write_text(render_pyproject(proj))
        print(f"wrote pyproject.toml (deps from {REPO.name}/pyproject.toml)")
    elif what == "manifest":
        tools = asyncio.run(tool_entries())
        out = HERE / "manifest.json"
        out.write_text(json.dumps(render_manifest(proj, tools), indent=2) + "\n")
        print(f"wrote manifest.json ({len(tools)} tools, version {proj['version']})")
    else:
        raise SystemExit(f"unknown target: {what}")


if __name__ == "__main__":
    main()
